[main]
# name = ["message to print", "must be in separated channel for punishment messages", "must suppres output for discord"]
reenter = ["Пользователь USER попытался перезайти на сервер имея активное наказание", "0", "0"]

set_headmod = ["Пользователь AUTHOR выдал пользователю USER должность главного модератора", "0", "0"]
add_mod = ["Пользователь AUTHOR добавил пользователя USER в список модерации", "0", "0"]
rem_mod = ["Пользователь AUTHOR удалил пользователя USER из списока модерации", "0", "0"]

set_log_channel = ["Пользователь AUTHOR установил канал CHANNEL в качестве канала для логгирования", "0", "0"]
set_punish_channel = ["Пользователь AUTHOR установил канал CHANNEL в качестве канала для логгирования наказаний", "0", "0"]
set_talk_channel = ["Пользователь AUTHOR установил канал CHANNEL в качестве канала для общения с ботом", "0", "0"]

set_mime_role = ["Пользователь AUTHOR установил роль ROLE в качестве роли мима", "0", "0"]
set_clown_role = ["Пользователь AUTHOR установил роль ROLE в качестве роли клоуна", "0", "0"]

role_not_found = ["Внимание, не обнаружена роль. Проверьте конфигурацию!", "0", "0"]